### ISSUE TITLE
Description View 작업

### ISSUE THREAD

**Issue by iDrogba** [DeveloperAcademy-POSTECH/MC2PocketCaddy#29]

**Comment by phainestha1** [comment]
6월 11일 현재 튜토리얼 파일이랑 원본 파일 코드가 달라 논의가 필요합니다.
논의 후 병합 진행합시다.

**Comment by phainestha1** [comment]
@iDrogba @Byeonjinha @jaehoon9186 @pig1606 @yoo86 
Target version 15.5 -> 15.0
